---
# Role: website
#
- include_tasks: apache.yml
- name: Deploy apache configuration for {{ website_domain }}
  template: src=apache2/sites-available/website.conf.j2 dest=/etc/apache2/sites-available/{{ website_domain }}.conf
  notify: reload apache2
  when: not website_customconf is defined
- name: Deploy custom apache configuration for {{ website_domain }}
  copy: src={{ website_customconf }} dest=/etc/apache2/sites-available/{{ website_domain }}.conf
  notify: reload apache2
  when: website_customconf is defined
- name: Enable apache configuration for {{ website_domain }}
  file: src=/etc/apache2/sites-available/{{ website_domain }}.conf dest=/etc/apache2/sites-enabled/{{ website_domain }}.conf state=link
  notify: reload apache2
  when: not ansible_check_mode
- name: Set default website (000-default.conf)
  file:
    src: "{{ website_domain }}.conf"
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: link
  notify: reload apache2
  when: website_default|bool
