---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: debian_9
    image: debian:stretch
  - name: debian_10
    image: debian:buster
provisioner:
  name: ansible
verifier:
  name: ansible
