---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Deploy expected default apache site configuration
    copy:
      src: 'site1.example.com.conf'
      dest: '/etc/apache2/sites-available/site1.example.com.conf'
      mode: 0444
      owner: root
      group: root
    register: site1_example_configuration
    check_mode: true
    diff: true

  - name: Deploy expected apache proxy site configuration
    copy:
      src: 'site2.example.com.conf'
      dest: '/etc/apache2/sites-available/site2.example.com.conf'
      mode: 0444
      owner: root
      group: root
    register: site2_example_configuration
    check_mode: true
    diff: true

  - name: Assert generated ansible site configuration
    assert:
      that:
        - not site1_example_configuration.changed
      msg: 'Unexpected change in /etc/apache2/sites-available/site1.example.com.conf'

  - name: Assert generated ansible site configuration
    assert:
      that:
        - not site2_example_configuration.changed
      msg: 'Unexpected change in /etc/apache2/sites-available/site2.example.com.conf'
